### ISSUE TITLE
POL 5 currently needs a restart to show the correct themed icons after a theme change

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#647]
When changing the theme, it's for most buttons required to show a different set of icons, that fit with the corresponding theme.
Currently most icons need a POL 5 restart to show the correct icons after the theme was changed.
Ideally the icons should change directly after a theme change, without the need to restart POL 5.

**Comment by plata** [comment]
If the icons are set in CSS directly, they will be changed automatically. 

The main problem is that we need a fallback mechanism:
- if app category icon is not themed, use the one from the ApplicationDTO
- if any other icon is not themed, use the one from the default theme
The second one should not be a big problem. If we always load the default theme and just do not set the icon in the other theme, it should take the default one. 
The default fallback mechanism of JavaFX themes does not work with `setStyle` because this always overrides the CSS. A solution could be to create a CSS for the button icon from the ApplicationDTO icon (see [here](https://stackoverflow.com/questions/24704515/in-javafx-8-can-i-provide-a-stylesheet-from-a-string)). So: first add the ApplicationDTO stylesheet, then the default stylesheet, then the dedicated stylesheet (e.g. the dark stylesheet). Then, if an icon (or a definition in general) is not themed in the dedicated stylesheet, it will automatically fall back to the next level, which is the default stylesheet. If it's not defined there, which can happen with a few category icons, you fall back to the ApplicationDTO stylesheet.

An alternative would be to wrap the currentTheme in the ThemeManager in an ObjectProperty  as in [this commit](https://github.com/PlayOnLinux/POL-POM-5/pull/646/commits/57a45cbd3a145972655ccaffb4e4a585a6c87621)

**Comment by plata** [comment]
Fixed by #704
