### ISSUE TITLE
Use the file manager for picking a local repository for scripts

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#776]
This would be much more intuitive than knowing you have to put `file:///` before a directory and typing it in manually.

**Comment by madoar** [comment]
The idea to use a file manager to pick a local repository is good, but the problem is how to identify which kind of repository the user wants to add?
If the user wants to add a git repository a file manager is useless to him, the same is true for the classpath repository. 
Therefore we would need to somehow identify what type of repository the user wants to add.

**Comment by plata** [comment]
This requires a small wizard with two steps:
1. select repository type (combobox)
2. select repository path (file chooser or text box)

**Comment by madoar** [comment]
@plata should we implement such a wizard? I'm not sure if we'll need additional work to style it correctly?

**Comment by plata** [comment]
I'm also a bit concerned about the look and feel. But I don't see another possibility currently.
