### ISSUE TITLE
[Medium] Implement the Command Line Interface (CLI)

### ISSUE THREAD

**Issue by qparis** [PlayOnLinux/POL-POM-5#8]
Currently, PlayOnLinux uses JavaFX as a main interface. The JavaFX implementation is located into com.playonlinux.ui.impl.javafx module. 
However, when --cli is passed, another implementation is used: com.playonlinux.ui.impl.cli. Currently, this implementation does not handle anything. 
We need to start working on it, so that PlayOnLinux can be run in command line mode. 

This implementation should be smart enough to accept programs arguments as command. For example, playonlinux --cli --run "An application" should automatically run "An application".

**Comment by seijikun** [comment]
What exactly should be possible with this cli? Some considerations:
* `playonlinux --app <shortcut_name> <arguments>`
* `playonlinux --prefix <prefixname> --run <cmd_to_run_within_prefix> <arguments>`
* `playonlinux --create <prefixname>`

Commands for starting the installation of applications through POL-Scripts is probably not desirable, since you could just use the gui then, couldn't you?
Also, should we use a CLI-Parser like [Apache CLI](http://commons.apache.org/proper/commons-cli/index.html) for this?

**Comment by qparis** [comment]
The idea is to implement a full CLI that will replace in some case the GUI. 
Then we are going to be able to control this CLI via command line (but not only).

I was thinking about replacing all windows by command line questions, and adding the ability to pass predefined answers.

Installing PlayOnLinux scripts via command line is very desirable because it can help for automated testing for example 

What do you think?

**Comment by RoninDusette** [comment]
That is an awesome idea. Having parity between the GUI and the CLI, in
terms of functionality, would be awesome. Automated testing was the
first thing that popped into my head. :)

On 21/05/2015, Quentin Pâris <notifications@github.com> wrote:
> The idea is to implement a full CLI that will replace in some case the GUI.
>
> Then we are going to be able to control this CLI via command line (but not
> only).
>
> I was thinking about replacing all windows by command line questions, and
> adding the ability to pass predefined answers.
>
> Installing PlayOnLinux scripts via command line is very desirable because it
> can help for automated testing for example
>
> What do you think?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/PlayOnLinux/POL-POM-5/issues/8#issuecomment-104448096


-- 
-----------------
Ronin Dusette
www.dusette.net

**Comment by seijikun** [comment]
Ahh, so you want to make the CLI like an alternative UI.
I don't know how this would play with automated testing, but we could go even one step further and use [something like ncurses](https://code.google.com/p/lanterna/).
![lanterna](http://wiki.lanterna.googlecode.com/git/images/screenshots/screenshot1.png)

**Comment by qparis** [comment]
I'm not sure if we are going to need ncurses. 
What about a really simple CLI (using println) so that we can also capture the output?

**Comment by seijikun** [comment]
Yeah, I agree. The amount of people interested in a cli instead of a ui are probably very limited, and for automated testing, the text-based cli would be an advantage. So ncurses is not necessarry:

I see two possibilities here, either we only have the commands within the cli-syntax and needed parameters are requested through the console, or we directly include the parameters within the cli.
So how about the following (module-based / git-like) syntax (either with or without parameters)?
_(Every module has static and instance-commands. Instance-cmd's use something existing, Static-cmd's modify / query something existing or create something new. Module-Parameters are used by the instance-cmd's)_
* `playonlinux repo`
    * **########## STATIC ##########**
    * `--list [--category=<category>]` : list all applications [with given category] in the repo
    * `--install <id>` : install application with id
* `playonlinux prefix [<prefix_name>]`
    * **########## STATIC ##########**
    * `--list` : print a list of prefixes
    * `--create <prefix_name>` : creates a new prefix with the given name
    * `--delete <prefix_name>` : deletes the given prefix with all shortcuts
    * **########## INSTANCE ##########**
    * `--info` : display some information for the given prefix
    * `--run <cmd>` : run a given command within the given prefix
* `playonlinux shortcut [<shortcut_name>]`
    * **########## STATIC ##########**
    * `--list` : List all available shortcuts
    * `--create <shortcut_name> --prefix="<prefix_name>" --cmd="<command>"` : create a new shortcut  for the given command within the given prefix
    * `--delete <shortcut_name>` : delete the given shortcut by name
    * **########## INSTANCE ##########**
    * `--info` : display some information for the given shortcut
    * `--run` : run the given shortcut

Some further considerations:
* Plugins (if something similiar is planned) could then simply register a new module in the cli and have their own cmd's within these modules.
* Of course we could create all commands (like delete) as Instance-cmd's - probably just a matter of taste. :)
* I think `repo --list` is enough, since it's more powerfull to use something like `playonlinux repo --list | grep -E "<regular_expression>"` instead of a custom-implemented search anyway.
* I used ***id*** as a parameter for install, since this is short and unique (I would print the id within the return of `--list`) and passing an application-name with multiple spaces in it seems somewhat impractical.
* I don't like how you would have to execute a shortcut (again because of the spaces).

And a question: What should we do with POL's output while the cli is being used? Since POL is heavily using async tasks - asynchronously logged Exceptions and other Debug-Output could be interrupting the flow.

**Comment by qparis** [comment]
I think what is really important here is to have implemented all the gui contracts (i.e. com.playonlinux.api) in CLI. 
* The interface UIMessageSender is responsible for sending instruction to the GUI. It is mainly asynchroneous in the case of JavaFX (because the main execution context is not allowed to access to the interface), but it should be far more easier for the command line interface. 
* The exception logging is not managed yet, but I'm not sure it will be asynchroneous

Then I guess that it will be easy to add command line modules that is using this CLI

**Comment by yawkat** [comment]
Also look into jline for improved CLI (similar to `readline`)

**Comment by Mannshoch** [comment]
If possible it should be possible to control some aspects from PlayOnLinux from outside PlayOnLinux in the same way then from inside.
Also I would prefer to control Inside POL with MS Powershell. Its possible to design the command in Powershell be 	identical like in Linux. Also the other commands in Powershell are similar or identical to use like in Linux.

**Comment by qparis** [comment]
(Done but it can be improved)
