### ISSUE TITLE
sort engines in "Containers" tab

### ISSUE THREAD

**Issue by plata** [PlayOnLinux/POL-POM-5#888]
Sort the engines in the combobox which allows you to change the engine of a container.

**Comment by madoar** [comment]
I'm not sure we should hold on to the combobox.
Currently the combobox has no implemented behavior.
In addition we've discovered before that's the combobox is quite unhandy because it contains such a large list of possible engine replacements, therefore I would suggest to add a wizard to change the engine.

**Comment by plata** [comment]
Also fine for me. Maybe we should just remove the combobox then not to confuse people.

**Comment by madoar** [comment]
When we want to do this correctly (as in provide the change engine functionality), I this is superseded by #702 and #620.

**Comment by plata** [comment]
Yes.
